# Site settings
title: Bitglass Engineering
email: noreply@bitglass.com
description: > # this means to ignore newlines until "baseurl:"
    Bitglass Engineering blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bitglass.com" # the base hostname & protocol for your site
twitter_username: bitglass
github_username:  bitglass-inc

# Build settings
markdown: kramdown
